---
# tasks file for smarthome

- name: Upgrade packages
  apt: upgrade=dist update_cache=yes

- name: configure WIFI
  copy: src=wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf

- name: Install a list of packages
  apt: "name={{ packages }}"
  vars:
    packages:
    - libavahi-compat-libdnssd-dev
    - python-pip
    - python3-pip
    - g++
    - git
    - make
    - monit
    - tree
    - mc
    - autossh
    - telnet
    - memcached

- include_role:
    name: zabbix-agent    

- name: Recursively change ownership of a directory
  file:
    path: /var/lib/smarthome
    state: directory
    recurse: yes
    owner: root
    group: root
    
#todo copy scripts, crontab, logrotate
